import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ReactNode } from "react";
import { AbstractIntlMessages, hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import MainLayout from "../_layouts/MainLayout";
import { locales } from "@/i18n/config";
import { notFound } from "next/navigation";

type Props = {
  children: ReactNode;
  params: { locale: string };
};

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Readonly<Props>) {
  const { locale } = await params;

  if (!hasLocale(locales, locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`${interSans.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <MainLayout>
            {children}
          </MainLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
